name: Run ESLint & Build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init node env
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: npm install
      run: npm ci
    - name: Test
      run: npm run test
    - name: Check ESLint
      run: npm run lint
    - name: Build product
      run: npm run build
      env:
        CI: true
